### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by dmgolembiowski** [edgedb/edgedb-vim#1]
Hi dev(s),

What's the setup on this monster like for a Debian/Ubuntu system?
Do I clone it to `~/.vim/{here}`? Does the `Makefile` hold all of the power?

**Comment by vpetrovykh** [comment]
You don't need the `Makefile` or anything else from the `_generator` directory for the plugin to work, those are for development. That being said, they shouldn't affect anything if you clone the repository into `~/.vim/pack/edgedb/start/{here}` (see the [vim docs](https://github.com/vim/vim/blob/247bf0de465411e4ebb1c0fe1a9e07f4a7f77e91/runtime/doc/repeat.txt#L515)).

(I'm assuming a relatively recent version of vim).

**Comment by dmgolembiowski** [comment]
Wonderful, thank you!
